### ISSUE TITLE
ModuleNotFoundError: No module named 'musical.denovo'

### ISSUE THREAD

**Issue by JoseFrancoAlvarez** [parklab/MuSiCal#60]
Using example full pipeline

![Screenshot 2022-06-20 at 18 01 08](https://user-images.githubusercontent.com/33030146/174649663-6a26eebf-076a-4df6-be66-535b5a171bf1.png)

**Comment by Hu-JIN** [comment]
Could you make sure MuSiCal is properly installed and jupyter notebook is using the correct kernel that has MuSiCal installed? The line you were running did not involve MuSiCal.
