### ISSUE TITLE
Small bug in remove_samples_based_on_gini?

### ISSUE THREAD

**Issue by ampregnall** [parklab/MuSiCal#62]
Two small + related issues with multiple potential solutions: I tried using the remove_samples_based_on_gini method after performing an extraction with H from the DeNovo sig class and my mutation count matrix X — loaded as a pandas DataFrame per the example_full_pipeline.ipynb — as my inputs. This resulted in a NotImplentedError which I traced back to the `mad = np.abs(np.subtract.outer(x, x)).mean()`  line in the gini method of preprocessing.py. The problem seems to be that pandas no longer supports the outer method on DataFrames or Series. Converting the DataFrame to an numpy array fixed the problem, so I think some clearer documentation about the expected data types for the inputs and/or a conversion of DataFrames to arrays within the method would help. Similarly, if you pass H as a DataFrame as opposed to an array, you get a TypeError for the `h_norm = h/np.sum(X, axis = 0)` line in the remove_samples_based_on_gini method, since that operation isn't supported on DataFrames. Same possible fixes would work!

**Comment by Hu-JIN** [comment]
Thanks for reporting these issues! We'll fix them as soon as possible.

**Comment by Hu-JIN** [comment]
Fixed in https://github.com/parklab/MuSiCal/commit/59b68f7f47a224a0b973e23fb72cd9c08c743e89
