### ISSUE TITLE
Refitting example

### ISSUE THREAD

**Issue by mandronescu** [parklab/MuSiCal#73]
Hello, 

I am trying to use the refitting example, however, I cannot find "musical.refit" in the package. Should I use "musical.assign" or "musical.assign_grid"?

Thank you!

**Comment by Hu-JIN** [comment]
Hi,

Thanks for trying out our package. The refit module can be accessed through `musical.refit`, and the refit function within that module can be called with `musical.refit.refit()`, as was used in the refitting example. Perhaps that solves the issue?

**Comment by mandronescu** [comment]
Hello, thank you for your prompt response. 
When I try `musical.refit`, I get `AttributeError: module 'musical' has no attribute 'refit'`. I see in the API `musical.DenovoSig`, `musical.assign` etc, but no `musical.refit`.

Thanks.

**Comment by mandronescu** [comment]
Hello, thank you for the prompt response. 
It looks like the package doesn't install correctly, because `__init__.py` under the installation directory didn't have `refit` under `__all__`, so I was getting `AttributeError: module 'musical' has no attribute 'refit'`. I added refit manually, and it works. 

Also, the catalog data doesn't get copied either, so `musical.load_catalog()` didn't find the `.csv` files. I copied them manually and it works. 

Thank you.

**Comment by Hu-JIN** [comment]
Hi, the catalog issue is resolved in https://github.com/parklab/MuSiCal/issues/71. If you uninstall, clone the most updated repo, and install again, it should work. Apologies for that. 

I don't fully understand the refit issue though. Maybe I'm missing something, but in `__init__.py`, the module `musical.refit` is referred to, which means that all functions within `musical.refit`, including `musical.refit.refit()` is callable. Could you send the code that you are running which can reproduce the error? Thanks.

**Comment by mandronescu** [comment]
I reinstalled, and both the catalog and the refit module work now. 

Thank you for a great tool!

**Comment by Hu-JIN** [comment]
Sounds good. Glad it's resolved with the reinstallation.
