### ISSUE TITLE
Run MuSical refitting step sing customized set of signatures

### ISSUE THREAD

**Issue by itigupta2429** [parklab/MuSiCal#79]
Hi Team,

Thank you for developing this incredibly useful tool!

I was running the refitting module by supplying a specific tumor type in the following command:
`catalog.restrict_catalog(tumor_type='Skin.Melanoma')
`
I was wondering if there is a way to input a custom set of SBS signatures (e.g., SBS1, SBS6, SBS11) for this analysis? The ability to supply specific signatures would greatly enhance the accuracy and insights from my data.

Thank you in advance!

**Comment by Hu-JIN** [comment]
Hi, 

Thanks for the interest in our tool. You can supply your custom set of signatures as W and use it in the analysis. As you can see in the example here: https://github.com/parklab/MuSiCal/blob/main/examples/example_refitting.ipynb, after the line you mentioned above, there is `W = catalog.W`. So all you need in the end is a dataframe of a set of signatures.
